### ISSUE TITLE
id des critères et tests

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#1]
Dans la version précédente, il était facile d'élaborer des documents en pointant sur les critères et tests du site RGAA 3 du Référentiel technique. En effet, les critères était identifier par "crit-1-10" correspondant au critère 1.10 et les tests par "test-10.13.3" correspondant au test 10.13.3. Il était donc facile d'extrapoler sur l'ensemble des tests et critères.

La génération type CMS utilisée dans la nouvelle version rend très pénible la création de document référençant le RGAA puisqu'il faut à chaque fois rechercher le bon id dans le code. Dans les exemples ci-dessus, le critères 1.10 a pour id "title-critre-110-a-chaque-lgende-dimage-est-elle-si-ncessaire-correctement-relie-limage-correspondante-" et le test 10.13.3 n'a quant à lui plus de id (cas de tous les tests maintenant).

**Comment by vmaucorps** [comment]
Une évolution est en cours de livraison pour traiter ce point.

**Comment by GiuseppeROSA** [comment]
Super  et  merci !

**Comment by GiuseppeROSA** [comment]
Pour information, de très nombreux liens sont "morts". Liste non hexaustive :

Test 10.6.1 : Dans chaque page Web, chaque lien texte signalé uniquement par la couleur et dont la nature n'est pas évidente a-t-il un rapport de contraste supérieur ou égal à 3:1 par rapport au texte environnant ?
    - le "lien texte" pointe en fait sur la définition de "lien image
    
Critère 12.10 [A] Dans chaque page Web, les groupes de liens importants (menu, barre de navigation...) et la zone de contenu sont-ils identifiés hors cas particuliers ? 
    - plus de lien sur "hors cas particulier"
    
Test 12.2.1 : Dans chaque ensemble de pages, chaque page ayant un menu de navigation vérifie-t-elle ces conditions (hors cas particuliers) ? 
   - lien "hors cas particulier" pointant vers "critres-122--123" au lien de "critres-122-123"
    
Critère 3.3 [AA] Dans chaque page Web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ? 
   - tous les liens "hors cas particulier" pointent vers "#critres-33--34" au lien de "#critres-33--34"
   - les liens vers la définition des tailles de polices par défaut arrivent également sur une page 404

**Comment by Etat-Plateforme** [comment]
Merci Guiseppe. Il y a eu une nouvelle livraison pour corriger certains points que tu listais. Nous allons vérifier qu'il n'y a pas eu d'effet de bord lors de l'import.

Pour information, nous utilisons la version DM déposée ici pour générer les pages du référentiels mis à disposition sur http://references.modernisation.gouv.fr/rgaa-3-0. Les problèmes que tu pointes sont donc plutôt en lien avec cette version consultable en ligne plutôt que sur le référentiel lui-même.

Pourrais-tu utiliser le formulaire de contact du site web pour signaler ce genre d'anomalies pour que ce dépôt soit exclusivement consacré au référentiel ?

Je te garantie que le temps de traitement sera le même et cela nous permettra de capturer d'éventuels besoins de mise à jour suite à une nouvelle version des WCAG par exemple.

Merci d'avance.

**Comment by GiuseppeROSA** [comment]
Très bien, c'était Philippe qui m'avait demandé de poster sur Github, mais j'utiliserai dorénavant le formulaire de contact.
Avez-vous une idée des délais pour les correctifs car j'ai différentes présentation dont certaines en cours de rédaction, avec de nombreux lien vers le référentiel et je n'arrête pas de revenir dessous pour modifier les liens morts.

Cordialement

**Comment by OlivierNourry** [comment]
Giuseppe,
nous sommes en train d'étudier le problème, je reviens vers toi lorsque j'ai une date de livraison.
Merci pour ta vigilance, et désolé pour le désagrément.
