### ISSUE TITLE
contraste des placeholder

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#10]
Le référentiel devrait sans doute préciser dans une note technique ou un cas particulier si les tests de contraste s'applique sur le placeholder. WCAG semble dire que oui mais d'une part ça reste assez lourdingue à gérer (obligé de passer par des -moz,-webkit, etc), d'autre part le respect de ce critère peut aboutir à une situation ou l'utilisateur va croire qu'il s'agit de texte déjà saisie dans le champ.

**Comment by access42** [comment]
Merci beaucoup de votre retour.

L'attribut <code>placeholder</code> est censé permettre d'indiquer des exemples de saisie ce qui serait contradictoire avec le fait d'accepter que certains utilisateurs ne les distinguent pas du fait de l'utilisation de contraste insuffisant.

Pour rappel, <code>placeholder</code> n'est pas pris en charge par RGAA qui s'aligne sur la position de WCAG sur ce sujet. Il s'agit donc d'une valeur par défaut quelconque qui nécessite de posséder des contrastes suffisants pour être perceptible.
Enfin, le critère sur les contrastes précise que l'auteur a le choix entre assurer nativement des contrastes suffisants ou proposer un dispositif qui permette d'assurer des contrastes suffisants ce qui peut permettre de prendre en charge la problématique que vous soulevez.

À noter également que ce problème d'utilisabilité de <code>placeholder</code> est l'une des raisons qui ont poussé WCAG à en refuser la prise en charge.

Nous ne voyons pas de raison de modifier cette position.

**Comment by goetsu** [comment]
> L'attribut placeholder est censé permettre d'indiquer des exemples de saisie ce qui serait contradictoire avec le fait d'accepter que certains utilisateurs ne les distinguent pas du fait de l'utilisation de contraste insuffisant.

il peut tout à fait être utilisé pour afficher des exemples de saisies "décoratifs" qui ne sont pas pour autant des formats de saisie obligatoire. De plus ces exemples pourrait également être repris dans dans un attribut title.

> Pour rappel, placeholder n'est pas pris en charge par RGAA qui s'aligne sur la position de WCAG sur ce sujet. Il s'agit donc d'une valeur par défaut quelconque qui nécessite de posséder des contrastes suffisants pour être perceptible

ok mais ce n'est indiqué nul part justement c'est bien là le problème car cela laisse le doute planer

**Comment by Etat-Plateforme** [comment]
Je ne comprends pas bien la notion d'exemple "décoratif". Le fait que l'exemple soit repris dans un attribut title ne sera d'aucune utilité pour les utilisateurs sans lecteur d'écran mais pour qui la prise en compte du contraste est indispensable.

**Comment by goetsu** [comment]
@Etat-Plateforme exemple un placeholder "rue jean moulin" pour un champ "rue" ou "paris" pour un champ ville.

Pour le title il a lui un contraste suffisant, certes il ne s'affiche pas à la prise de focus clavier (sauf sur edge et ie11 à priori) mais ce n'est pas pire qu'un title de lien qui lui est autorisé comme solution pour rendre explicite un lien ou indiquer poids/format/etc bien que difficilement utilisable pour les utilisateurs de zoom ou utilisateur clavier)

Enfin dans la mesure où le placeholder est utilisé pour indiquer un format de saisie requis et non juste pour du décoratif mais que le message d'erreur reprend bien ce format/exemple cela n'est pas bloquant pour l'utilisateur.

PS: si rien précisé/corrigé suite à ce retour il sera utile d'avoir un label wont-fix ou équivalent

**Comment by goetsu** [comment]
@Etat-Plateforme le label traitée me semble pas très utile vu que ce qui est avec un status closed est forcement traité, un label "aucun changement prévu" ?
Ahma je reste preneur de retour sur mon dernier commentaire
