### ISSUE TITLE
test 1.2.4 image vectorielle (svg) décorative

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#12]
Si l'objectif est de faire en sorte que rien ne soit vocalisé car c'est un élément décoratif, le test est à revoir complètement : 
- il demande le respect d'une des conditions au lieu de toutes 
- il demande à tort l'utilisation du role="img" ce qui provoque la vocalisation de "image" 
- il ne prend pas en compte l'usage de <text> comme source d'alternative
- il demande de tester les images "possédant une alternative" alors que le test demande justement qu'il n'y en ai pas donc les éléments rentrant dans le champ d'application sont forcement non conformes

Par ailleurs, les autres conditions bien que valables devraient être non applicables : 
- si le svg est en aria-hidden="true"
- si le svg est masqué via hidden ou display:none

**Comment by access42** [comment]
Merci beaucoup de votre retour.

Une issue a été ouverte, suite à votre dernier retour sur ce sujet lors de l'appel à commentaire public.
Elle sera traitée lors de la prochaine mise a jour.
