### ISSUE TITLE
test 1.3.6 image vectorielle (svg) porteuse d'information

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#13]
Ce test présente plusieurs problèmes majeurs : 
- il demande de tester les images "possédant une alternative" donc une image porteuse d'information sans alternative ne sera pas non conforme
- les solutions pour restituer une alternative proposées ne sont pas conforme avec la base de référence (en particulier <title> et <desc> ne fonctionnent pas sur Voiceover) car à l'heure actuelle seul l'usage d'un <text> en opacity 0 permet de restituer convenablement une alternative dans toutes les combinaisons (et il faut alors ne pas utiliser de role img mais mettre la notion "image" dans le <text>) 
- il demande le respect d'une des conditions au lieu de role img + un des autres
- il manque d'autres éléments pour assurer une restitution correcte dan les lecteurs d'écrans

Donc en l'état quelqu'un qui respecte ce test sera de toute façon forcement non conforme au test 1.3.7

Les règles à suivre sont récapitulée sur http://www.accede-web.com/notices/html-css-javascript/6-images-icones/6-2-svg-images-vectorielles/ suite à des tests que j'ai réalisé http://codepen.io/goetsu/pen/BNKoeG

**Comment by access42** [comment]
> * il demande de tester les images "possédant une alternative" donc une image porteuse d'information sans alternative ne sera pas non conforme
> les solutions pour restituer une alternative proposées ne sont pas conforme avec la base de référence (en particulier et <desc> ne fonctionnent pas sur Voiceover) car à l'heure actuelle seul l'usage d'un <text> en opacity 0 permet de restituer convenablement une alternative dans toutes les combinaisons (et il faut alors ne pas utiliser de role img mais mettre la notion "image" dans le <text>) </li> <li>il demande le respect d'une des conditions au lieu de role img + un des autres</li> <li>il manque d'autres éléments pour assurer une restitution correcte dan les lecteurs d'écrans</li> </ul> <p>Donc en l'état quelqu'un qui respecte ce test sera de toute façon forcement non conforme au test 1.3.7</p> <p>Les règles à suivre sont récapitulée sur <a href="http://www.accede-web.com/notices/html-css-javascript/6-images-icones/6-2-svg-images-vectorielles/">http://www.accede-web.com/notices/html-css-javascript/6-images-icones/6-2-svg-images-vectorielles/</a> suite à des tests que j'ai réalisé <a href="http://codepen.io/goetsu/pen/BNKoeG">http://codepen.io/goetsu/pen/BNKoeG</a></p>

Merci beaucoup pour votre retour et la référence à votre suite de test.

Comme indiqué dans les commentaires publiés suite à l'appel public à commentaires, le critère 1.3.6 va faire l'objet d'une adaptation lors de la prochaine mise à jour.
Les dispositifs proposés par AcceDe Web seront étudiés.

Merci beaucoup pour votre page de test qui nous sera d'une grande utilité.

En revanche nous ne comprenons pas bien certains résultats. Ainsi la section 7 "svg avec role img, élément title et aria-label" semble indiquer que la combinaison <code>aria-label</code>, <code>role="img"</code>, <code>title</code> actuellement exigée par le RGAA, donne pour toutes les versions de lecteurs d'écrans testées un résultat satisfaisant, y compris avec VoiceOver.

Avons-nous mal compris quelque chose ?

**Comment by goetsu** [comment]
> Ainsi la section 7 "svg avec role img, élément title et aria-label" semble indiquer que la combinaison aria-label, role="img", title actuellement exigée par le RGAA, donne pour toutes les versions de lecteurs d'écrans testées un résultat satisfaisant, y compris avec VoiceOver.

oui mais il faut les trois (aria-label + role="img" + élément title ) et non juste un de ces éléments comme le dit le test

**Comment by Etat-Plateforme** [comment]
Encore merci pour votre contribution.
Nous prendrons en compte ces éléments dans la prochaine version du RGAA.
