### ISSUE TITLE
8.10

### ISSUE THREAD

**Issue by fhalna** [DISIC/rgaa_referentiel#17]
Test 8.10.1 : Dans chaque page Web, chaque texte dont le sens de lecture est différent du sens de lecture par défaut vérifie-t-il ces conditions ?
- Le texte est contenu dans une balise possédant un attribut dir ;
- La valeur de l’attribut dir est conforme (rtl ou ltr) ;
- La valeur de l’attribut dir est pertinente.

Test 8.10.2 : Dans chaque page Web, chaque changement du sens de lecture (attribut dir) vérifie-t-il ces conditions ?
- La valeur de l’attribut dir est conforme (rtl ou ltr) ;
- La valeur de l’attribut dir est pertinente.

<hr>

le test 8.10.1 ne se limiterait-il pas à la présence de l'attribut dir et le test 8.10.2 à la pertinence de cet attribut ?

Test 8.10.1 : Dans chaque page Web, chaque texte dont le sens de lecture est différent du sens de lecture par défaut vérifie-t-il ces conditions ?
- Le texte est contenu dans une balise possédant un attribut dir ;

Test 8.10.2 : Dans chaque page Web, chaque changement du sens de lecture (attribut dir) vérifie-t-il ces conditions ?
- La valeur de l’attribut dir est conforme (rtl ou ltr) ;
- La valeur de l’attribut dir est pertinente.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Les tests ont été modifiés en conséquence. Ces modifications sont indexées dans la note de révision.
