### ISSUE TITLE
img, canvas, svg, object type image dans <button> et <a>

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#18]
Bonjour, 

Sauf erreur de ma part le document d'accompagnement ne précise pas un changement important par rapport au RGAA 2.2 à savoir que les cas des liens images et des liens vectoriels est désormais traité dans la thématique Liens au lieu de la thématique Images. 

Par ailleurs ces cas ne sont pas clairement exclu au travers des tests de la thématiques images du RGAA 3.0. 

Il pourrait être utile de mentionner au travers du glossaire ou d'une note technique pour l'ensemble des critères de cette thématique ainsi que pour la thématique multimédia afin de lever cette ambiguïté.

Par ailleurs, le cas des boutons images ou boutons vectoriels (button > img/canvas/object/svg) ne semble pas pris en compte du tout par le RGAA 3.0

**Comment by xam1311** [comment]
Bonjour,
Je rebondi là dessus, car justement les animations SVG, infographies animées ou animation pure sont de plus en plus courantes, ce serait bien d'avoir des indications pour les svg.
Merci.

**Comment by goetsu** [comment]
@xam1311 tu peux également regarder https://github.com/DISIC/rgaa_referentiel/issues/13 et https://github.com/DISIC/rgaa_referentiel/issues/12

**Comment by xam1311** [comment]
oui le #12 répond parfaitement à cela, par contre si on fait un audit RGAA avec les tests actuels on aura une validité valable 18 mois sur des tests qui auront évolués n'est-ce pas ?

**Comment by Etat-Plateforme** [comment]
Merci pour ce retour.

## Concernant les images-liens
Nous prenons bonne notre de votre remarque. Nous étudierons la possibilité d'enrichir la définition de glossaire d'«&nbsp;image porteuse d'information&nbsp;» pour apporter cette précision.

@goetsu, nous ne comprenons pas, en revanche, en quoi la thématique Multimédia pourrait être impactée. Pourriez-vous étayer votre remarque d'un exemple ?

## Concernant les boutons contenant une image

Selon le contexte, la problématique de l'utilisation d'éléments <code>button</code> contenant une image ou une image vectorielle est prise en charge par :

- le critère 11.9, test 11.9.1 dans le cadre d'un formulaire ;
- le critère 7.1, test 7.1.1 lorsque le bouton est contrôlé par JavaScript.

Dans les deux cas, l'image ou l'image vectorielle joue le rôle d'intitulé ou de nom de l'élément concerné.

Pour les mêmes raisons que pour les images-liens, cette précision sera donc apportée via la définition de glossaire d'«&nbsp;image porteuse d'information&nbsp;».

**Comment by Etat-Plateforme** [comment]
Désolé pour cette prise en compte tardive.
@xam1311 pourriez-vous préciser votre point (si ce dernier est toujours d'actualité).
L'audit RGAA porte sur des données et une configuration d'un site à un instant donné. Les tests réalisés n'ont pas une validité temporelle particulière.

**Comment by goetsu** [comment]
Concernant les images - liens, la question est de savoir si j'ai un canvas, svg, object, embed dans un lien si les tests de la thématique multimédia sont applicables ou non. Il me semblerait que non (au moins en partie) puisqu'ils relèvent de la thématique lien mais cela nécessite une analyse plus précise.

**Comment by Etat-Plateforme** [comment]
Merci de ces précisions que nous prendrons en compte dans les travaux de la nouvelle version du RGAA.

**Comment by goetsu** [comment]
Concernant les boutons contenant une img canvas, svg, object je comprend tout à fait la répartition proposé mais à minima il faudrait une définition de glossaire sur "contenu de la balise" du test 11.9.1 pour préciser que cela comprend également le alt d'une img, le texte dans un canvas, le aria-label d'un svg, etc dans un button.

De plus, ce test vérifie directement la pertinence sans test de présence préalable contrairement au autres tests du rgaa (exemple on a bien un test sur l'absence de lien vide mais de test sur l'absence de button vide ou tests sur image qui vérifie d'abord présence du alt avant de vérifier pertinence). 

Enfin dans le cas de canvas et svg il devrait également être nécessaire de vérifier la restitution dans la base de référence (comme pour thématique image, script)
