### ISSUE TITLE
Lisibilité des liens de correspondance WCAG

### ISSUE THREAD

**Issue by armonyaltinier** [DISIC/rgaa_referentiel#18]
Dans le référentiel technique, il n'est pas évident que les références de correspondance vers les critères WCAG ou les techniques suffisantes ou échecs sont des liens, et ceux-ci ne sont pas visibles par rapport au texte environnant, ce qui contrevient au critère 10.6.

Anomalie remontée par Ludovic Gaillard.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Les liens sont dorénavant soulignés.
