### ISSUE TITLE
note technique en trop critère 1.1

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#19]
les notes techniques présentent une note concernant le critère 1.1 qui porte sur l'élément svg hors aucun test ne fait référence à l'élément svg sur le critère 1.1 il doit s'agir d'un reste de la version de travail

Note en question https://references.modernisation.gouv.fr/referentiel-technique-0#title-critre-11-a

**Comment by Etat-Plateforme** [comment]
Merci pour votre vigilance.

La note sera supprimée à la prochaine mise à jour.
