### ISSUE TITLE
11.1.5 et 11.10.10

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#2]
rappel des tests : 
11.1.5  Chaque champ de formulaire qui utilise un attribut title comme étiquette, vérifie-t-il une de ces conditions ?
-     L’attribut placeholder est absent ;
-     L’attribut placeholder est identique à l’attribut title.

11.10.5 Chaque champ de formulaire qui utilise un attribut title comme aide à la saisie, vérifie-t-il une de ces conditions ?
-     L’attribut placeholder est absent ;
-     L’attribut placeholder est identique à l’attribut title.

---

Problème

J'avoue ne pas comprendre la logique de ces test.

Tout d'abord dans le cas des title utilisé comme aide à la saisie on pourrait remarquer que si un title est utilisé comme aide à la saisie post validation c'est qu'a priori le champ a déjà été rempli et donc il n'y a plus de placeholder dans le champ (sauf à ce que le mécanisme de validation vide les champs en erreurs)

Par ailleurs, les tests que j'ai réalisé sur VoiceOver, Jaws16 et NVDA dernière version et tous vocalisent le title et le placeholder quand les deux sont présent je ne vois donc pas l'intérêt de demander qu'il soient identiques

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

La contrainte de fournir un `title` identique au `placeholder` vient de la formule de calcul du nom accessible ou de la description accessible proposée par le [document du W3C : HTML to Platform Accessibility APIs Implementation Guide](https://www.w3.org/TR/html-aam-1.0/).

Cette formule de calcul est la suivante :

> - Use `aria-labelledby`
> - Otherwise use `aria-label`
> - Otherwise use the associated `label` element
> - Otherwise use the `placeholder` attribute
> - Otherwise use the `title` attribute
> - If none of the above yield a usable text string there is no accessible name

Elle implique que lorsque le `placeholder` est présent, le `title` ne devrait pas être restitué en tant que nom accessible pour l’élément.

Le RGAA, comme WCAG, refuse l’utilisation de placeholder pour labelliser un élément de formulaire. Donc les développeurs et intégrateurs s’ils utilisent un `title` peuvent créer une situation où seule la valeur de `placeholder` va être restituée. Si cette valeur ne permet de labelliser le champ de formulaire, le `label` risque d’être simplement absent en restitution. La contrainte que le `placeholder` soit identique au `title` permet de s’assurer que la valeur faisant office de `label` sera systématiquement mise à disposition.

Le fait que les lecteurs d’écrans restituent les deux valeurs n’est pas déterminant dans ce choix, en effet ces derniers ou d’autres lecteurs d’écrans pourraient décider de se conformer à cette formule de calcul, ce qui causerait un problème important pour l’utilisateur.

Nous ne voyons pas de raison de modifier cette position du RGAA.
