### ISSUE TITLE
Menu et NVDA

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#2]
Je ne sais pas si c'est spécifique à mon poste mais le fonctionnement de NVDA (testé en version 2014.4 et 2015.2) sur Firefox (38.0.5) perturbe le fonctionnement du menu. L'utilisation de la touche "Entrée" sur l'item "Documents de référence" fonctionne (ouvre le sous-menu) mais cette fonctionnalité de fonctionne plus sur les items suivants ("Les enjeux de l'accessibilité numérique", "Référentiel" et "Ressources"). Sans NVDA, ces fonctionnalités fonctionne correctement.

**Comment by Etat-Plateforme** [comment]
Nous prendrons en compte ce retour lors dans la prochaine évolution du site qui devrait avoir lieu début 2016.
