### ISSUE TITLE
prise en compte embed critère 1.2

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#20]
il me semble manquer un test portant sur l'élément embed pour le critère 1.2. Exemple : 
Test 1.2.x : Chaque image embarquée sans légende (balise embed avec l'attribut type="image/...") non porteuse d'information, vérifie-t-elle ces conditions :
- l'image embarquée ne possède pas d'attribut title
- l'image embarquée ne possède pas d'attribut aria-label
- l'image embarquée ne possède pas d'attribut aria-labelledby
- l'image embarquée ne possède pas d'attribut aria-describedby

**Comment by Etat-Plateforme** [comment]
Encore merci pour votre vigilance.

Le test manquant sera ajouté à la prochaine mise à jour.
