### ISSUE TITLE
prise en compte aria-label, aria-labelledby, aria-describedby critère 1.2

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#21]
ces attributs aria lorsqu'ils sont non vide peuvent entrainer la restitution de contenu sur les images décoratives, il est donc nécessaire d'en interdire leur utilisation sur les img / canvas / object / area décoratifs ainsi que l'attribut title sur les object / canvas

**Comment by Etat-Plateforme** [comment]
Merci pour votre retour.

Nous prenons bonne note de votre remarque. Les tests concernés seront corrigés en conséquence.
