### ISSUE TITLE
captcha audio / video / canvas et embed / object non type image

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#22]
les tests des critères 1.4 et 1.5 ne couvrent pour l'instant pas le cas de captcha utilisant ces éléments, ils pourraient etre couverts via les tests 4.1.1, 4.1.2, 4.1.3 mais ça me semble pas des plus limpides et de plus il y a un cas particulier pour ce critère qui dit :

> ```
> Il existe une gestion de cas particulier lorsque :
> [...]
> le media temporel est utilisé comme un CAPTCHA ;
> le media temporel fait partie d'un test qui deviendrait inutile si la transcription textuelle, les sous-titres synchronisés ou l'audio-description étaient communiqués.
> Dans ces situations, le critère est non applicable.
> ```

De fait il semble opportun d'introduire des nouveaux tests dans la thématique multimédia pour couvrir le cas de ces éléments

Exemple : 
un site propose uniquement un captcha audio
un site proposant un captcha demandant de réécrire un texte affiché après une vidéo

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Comme vous l’indiquez, la prise en charge de ces types de captcha concerne le critère 4.22. 

Les éléments `video` et `audio` rentrent dans le périmètre du critère par l’intermédiaire des définitions de glossaire :

- « media temporel » : https://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#mdia-temporel-type-son-vido-et-synchronis
- « media non temporel » : https://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#mdia-non-temporel

Néanmoins, les tests sont incomplets, car ils ne réfèrent qu’aux seuls objets `object` et `embed`. Les tests ont été corrigés en conséquence. Ces modifications sont indexées dans la note de révision.
