### ISSUE TITLE
Compatible ou accessible aux technologies d'assistance ?

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#24]
Bonjour,

le test 7.1.1 demande de vérifier que le nom, le rôle, la valeur, le paramétrage et les changements d'états soient accessibles aux technologies d'assistance via une API d'accessibilité.
Dans le cas de l'utilisation d'ARIA et uniquement ce cas, le test 7.1.5 demande en complément que le composant d'interface soit correctement restitué par les technologies d'assistance vis à vis de la base de référence.

Il en résulte que dans un cas (utilisation d'ARIA) on doit vérifier la compatibilité par rapport à la base de référence mais que dans le cas ou le nom, le rôle, la valeur, le paramétrage et les changements d'états ne sont pas fournis via ARIA mais via des attributs html cette vérification ne doit pas être faite.

Pourriez vous expliquer les raisons de cette différence sachant que certains attributs html peuvent également présenter des problèmes de restitution dans les technologies d'assistance (l'attribut title notamment).

Par ailleurs la méthodologie de test associé au 7.1.5 restreint le test au code ARIA utilisé dans le cadre d'un motif de conception hors ARIA peut tout à fait être utilisé en dehors d'un motif de conception.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Il est en effet possible de générer des composants d’interface via JavaScript qui n’utiliseraient pas ARIA et qui seraient mal ou pas restitués.

Le test a été généralisé pour prendre en compte tous les cas.

> Test 7.1.5 : Chaque script qui génère ou contrôle un composant d’interface respecte-t-il une de ces conditions ?

Et une entrée de glossaire pour « composants d’interface » a été créée.

> Un composant d’interface est un élément avec lequel l’utilisateur peut interagir, par exemple un bouton, un lien, une zone de saisie. Certains composants peuvent être plus complexe par exemple un menu, une fenêtre de dialogue, un système d’onglet. Enfin un composant d’interface peut être basé sur des éléments natifs de HTML ou développés de toutes pièces avec JavaScript et l’API ARIA.

Ces modifications sont indexées dans la note de révision.
