### ISSUE TITLE
propriété bgsound 

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#24]
Le critère 4.18 mentionne une propriété bgsound, il me semble qu'il s'agit d'un élément et non d'une propriété. Par ailleurs cet élément devrait également être pris en compte dans le test 4.19 et comme moyen de diffusion dans la définition de media temporel

**Comment by Etat-Plateforme** [comment]
Merci pour votre vigilance.

<code>bgsound</code> est effectivement un élément, la correction sera effectuée lors de la prochaine mise à jour.

Cet élément n'étant pas standard (spécifique à Internet Explorer), il sera ajouté également une définition de glossaire pour signaler qu'il ne devrait jamais être utilisé en HTML4, HTML5 l'ayant déclaré «&nbsp;non conforme&nbsp;», son utilisation rendrait le critère 8.2 invalide.

Le critère 4.19 sera modifié en conséquence.
