### ISSUE TITLE
role="presentation" sur tableau de mise en forme

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#25]
le test 5.3.1 oblige l'ajout d'un attribut role="presentation" sur l'élément table hors cela rend impossible son utilisation pour d'autres role aria qui pourrait être totalement justifié par exemple : 

pour une liste mise en forme via un tableau : 
```html
<table role="list">
<tr role="listitem">
<td role="presentation"><img src="puce.png" alt=""/></td>
<td role="presentation">lorem ipsum</td>
</tr>
...
</table>
```
pour des onglets
```html
<table role="tablist">
<tr role="presentation">
<td role="tab">lorem ipsum</td>
<td role="tab">lorem ipsum</td>
</tr>
...
</table>
```

**Comment by Etat-Plateforme** [comment]
L'utilisation de tableaux pour faire de la mise en forme est encore fréquente. L'objectif du critère est d'éviter la restitution du rôle tableau quand il ne s'agit pas d'une présentation de données tabulaires.

L'API WAI-ARIA procède via un mécanisme de surcharge de rôle qui modifie la nature de l'élément restitué.

Référence : <a href="http://w3c.github.io/aria-in-html/#do" lang="en">2.6 What does adding a role do to the native semantics?</a>

Dans les deux exemples que vous citez, l'élément <code>&lt;table&gt;</code> ne sera pas restitué comme un tableau mais comme une liste d'une part, et une liste d'onglets d'autre part.

Il est inutile de signaler au navigateur, via la présence du rôle <code>presentation</code>, que l'élément <code>table</code> ne doit pas être restitué puisque l'auteur a modifié son rôle natif.

Le critère est donc en l'espèce non applicable.

Cela peut néanmoins induire une certaine confusion lorsque le fonctionnement de l'API WAI-ARIA n'est pas totalement approprié. Nous enrichirons la note de glossaire sur «&nbsp;tableau de mise en forme&nbsp;» pour expliciter ce type d'utilisation.
