### ISSUE TITLE
critère 10.7

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#25]
Les tests du critères 10.7 interdisent l'usage d'un outline 0 ou none néanmoins les WCAG 2.0 autorisent l'application d'un style à la prise de focus sans pour autant conserver un outline cf :

exemple donnée sur 
http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G149
http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/C15
http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G195
http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/SCR31

Le understanding du SC 2.4.7 indique bien 

> ```
> Note that a keyboard focus indicator can take different forms.
> ```

Ainsi que les exemples données :

> When text fields receive focus, a vertical bar is displayed in the field, indicating that the user can insert text, OR all of the text is highlighted, indicating that the user can type over the text.
>     When a user interface control receives focus, a visible border is displayed around it.

S'agissant donc d'une spécificité du RGAA par rapport à WCAG il est nécessaire que celle ci soit consigné dans les documents d'accompagnement du RGAA afin de permettre aux personnes ayant un site conforme WCAG de savoir quoi modifier pour devenir conforme RGAA

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Une note technique a été créée pour le critère 10.7.
