### ISSUE TITLE
critère 11.5

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#26]
Il me semble que le si nécessaire ici gagnerait à être explicité dans le glossaire pour indique que si par exemple emploi de https://www.w3.org/TR/WCAG20-TECHS/ARIA17.html ou de aria-describedby vers le titre du groupe ou title sur les champs pour différencier les groupes le critère devient non appliquable

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Les tests 11.5.1, 11.6.1 et 11.7.1 et l’entrée de glossaire « Bloc d’informations de même nature » ont été modifiés pour prendre en charge d’autres cas d’implémentations que `fieldset` pour les regroupements de champs. Ces modifications sont indexées dans la note de révision.
