### ISSUE TITLE
attribut colgroup et axis critère 5.8

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#26]
le critère 5.8 invalide la présence d'un attribut colgroup ou axis sur les tableaux de mise en forme néanmoins l'attribut axis est obsolète dans la spécification html5 et sera donc déjà de fait non conforme sur le critère 8.2. 

Il semble également que l'attribut colgroup n'existe pas en html5

**Comment by Etat-Plateforme** [comment]
Le référentiel technique du RGAA est destiné à prendre en charge HTML4, XHTML 1.0 et HTML5.

Dans ce contexte, les attributs <code>axis</code> et <code>colgroup</code> doivent être explicitement proscrits dans RGAA car ils peuvent, s'ils sont utilisés, perturber la restitution en induisant en erreur les technologies d'assistance sur la nature du tableau.

Lorsque le contenu est du HTML5, le critère sera non applicable de fait, ces deux attributs ne pouvant pas être utilisés et l'erreur de leur présence est déjà prise en charge, comme vous le soulignez, par le critère 8.2.

Il n'est donc pas nécessaire de modifier le critère 5.8.

**Comment by goetsu** [comment]
Dans ce cas pouvoir avoir sur d'autres cas, supprimé des tests portant sur des éléments / attributs non existant dans html5 (par exemple <frame> ou summary pour les tableaux de données)

**Comment by goetsu** [comment]
par ailleurs colgroup n'est pas un attribut mais un élément en html4

**Comment by goetsu** [comment]
@Etat-Plateforme la fermeture du ticket me semble prématurée
