### ISSUE TITLE
intitulé area avec ou sans contexte

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#27]
à l'heure actuelle l'élément area est couvert par 4 tests : 
- 1.1.2 qui vérifie présence du alt sur area
- 1.3.2 qui vérifie pertinence du alt + title identique si présent
- 6.2.3 qui vérifie pertinence du title de l'area
- 6.3.3 qui vérifie pertinence du alt de l'area hors contexte

Les tests 6.2.3 et 6.3.3 semblent inutiles puisque : 
- si le title est présent il doit être identique au alt au regard du 1.3.2 et donc forcement pertinent puisque le alt doit l'être
- le 1.3.2 n'autorise déjà pas l'utilisation du contexte de lien tel que défini https://references.modernisation.gouv.fr/referentiel-technique-0#contexte-du-lien notamment de aria-label ou aria-labelledby donc la vérification hors contexte est déjà fait par le 1.3.2

Par contre, puisqu'il y a un test spécifique sur la pertinence de l'intitulé des liens doublant une zone cliquable coté serveur (cf 6.1.3) il faudrait également: 
- vérifier pertinence du title des liens doublant une zone cliquable coté serveur en 6.2
- vérifier pertinence de l'intitulé des liens doublant une zone cliquable coté serveur hors contexte en 6.3

**Comment by Etat-Plateforme** [comment]
Merci pour votre retour qui concerne, à mon sens, donc deux sujets distincts.

## Concernant les balises <code>area</code>

Les deux séries de tests (auxquelles il faut ajouter le test 1.2.2) ne concernent pas le même type d'objet.

La vocation du test 1.3.2 est de prendre en charge les <a href="http://references.modernisation.gouv.fr/referentiel-technique-0#zone-non applicable">zones non cliquables</a> : <code>area</code> sans attribut <code>href</code> en HTML5 ou avec un attribut <code>nohref</code> en HTML4.

En revanche, le test 1.3.2 manque effectivement de précision dans sa rédaction. Le terme <q>zone</q> devrait être remplacé par <q>zone non cliquable</q> et pointer sur la définition ad'hoc.

Afin de rendre l'ensemble des tests cohérents (zone non cliquable en thématique image et zone cliquable en thématique liens), une opération de relecture et de mise à jour sera effectuée sur l'ensemble de la thématique Images et de la thématique Liens pour le cas des zones cliquables et non cliquables d'une image réactive coté client ou serveur.

L'opération de relecture sera fondée sur les propositions suivantes :

1. toutes les zones d'une image réactive sont traitées en thématique Images pour la présence de l'attribut alt ;
1. les zones non cliquables sont traitées en thématique images pour les zones décoratives ou informatives ;
1. les zones cliquables sont traitées en thématique Liens pour la pertinence du alt et du title.

Ces modifications seront prises en charge lors de la prochaine mise à jour.

## Concernant les liens doublant une zone réactive côté serveur

Les liens doublant une zone cliquable coté serveur sont un cas général de lien (il s'agit de lien de type <code>&lt;a href&gt;</code>, il n'y a donc pas de test à ajouter en 6.2 et en 6.3.

En revanche, nous remarquons que le test 6.1.3 est dans le même cas, il s'agit d'un cas général de lien.
Le test sera réévalué.
