### ISSUE TITLE
Motifs de conception

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#3]
A priori, le menu ne respecte pas les design patterns (motifs de conception) WAI-ARIA.

**Comment by jpv66** [comment]
Bonjour Giuseppe,

Peux-tu préciser ta remarque.
Le menu n'utilise pas de design pattern ARIA.

**Comment by GiuseppeROSA** [comment]
Bonjour Jean-Pierre,

Lorsqu'on est sur un menu classique on pense pouvoir naviguer uniquement avec la tabulation (ou à la rigueur les flèches de direction). Si on est sur un design ARIA, on pense se trouver sur un pattern ARIA. Je suis donc étonné de me trouver dans un cas encore différent ne répondant à aucun de ces modes de fonctionnement.

**Comment by jpv66** [comment]
Bonjour,
Oui, pour autant il ne s'agit pas d'une non-conformité.
Aria ne propose aucun modèle pour les menu de navigation de site.
Aria 1.1, en cours d'élaboration, proposera un modèle (site Navigator) qui actuellement en cours de relecture et est donc susceptible d'évoluer.
Il est effectivement d'usage de traiter les menus de navigation en rendant disponible les sous-menus à la prise de focus de la tabulation. Pour autant cela pose un problème car on oblige les utilisateurs à tabuler sur l'intégralité des liens du sous-menu pour atteindre le second item, ce qui rends l'utilisation de l'ensemble du menu laborieuse.
L'utilisation de toggle button, comme proposé ici, résoud ce problème : l'utilisateur tabule sur le premier niveau et choisi quel sous-niveau il désire ouvrir.
Le modèle concurrent est celui où l'intégralité du menu est utilisable avec les flêches de direction. Actuellement ce modèle est difficilement utilisable car, pour le rendre utilisable aux lecteurs d'écran, il faut utiliser le design pattern "menubar" qui n'est pas fait pour ça (il est dédié à la production de menu de commande dans un contexte applicatif).

**Comment by GiuseppeROSA** [comment]
Merci pour cette réponse détaillée. Je trouvais toutefois étrange que cela ne réponde pas de manière conventionnelle. Ce menu provient d'un template drupal ?
Concernant le "menubar" dédié à un contexte applicatif, je ne suis pas sur que les utilisateurs sachent faire la différence entre site et application. Pour ma part certains de mes interlocuteurs ne comprennent déjà pas la notion d'application web, de navigateur...
