### ISSUE TITLE
Pertinence des titres des boutons hors formulaires et hors js

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#31]
Le critère 6.2 demande de vérifier la pertinence des titre de liens.
Le 11.9 demande de vérifier la pertinence des intitulés des boutons dans les formulaires mais couvre également la pertinence des titre de bouton via 11.9.1

Rien ne couvre donc le cas des boutons hors formulaire ayant un titre non pertinent et hors js car en effet le critère 7.1 vérifie uniquement la présence d'un nom et non sa pertinence et par ailleurs le nom peut tout à fait être mis en place directement dans le html sans passer par un script.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Le contrôle de la pertinence d’un nom est apporté par le glossaire (http://www.references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#le-nom-le-rle-la-valeur-le-paramtrage-et-les-changements-dtats) qui précise : « un composant doit avoir un rôle et un nom appropriés ».

Néanmoins nous comprenons que cela est insuffisant, en conséquence un nouveau test 7.1.7 a été créé.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Le contrôle de la pertinence d’un nom est apporté par le glossaire (http://www.references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#le-nom-le-rle-la-valeur-le-paramtrage-et-les-changements-dtats) qui précise : « un composant doit avoir un rôle et un nom appropriés ».

Néanmoins nous comprenons que cela est insuffisant, en conséquence un nouveau test 7.1.7 a été créé.

> Test 7.1.7 Chaque script qui génère ou contrôle un composant d’interface vérifie-t-il ces conditions ?
- Le composant possède un nom pertinent.
- Le composant possède un rôle pertinent

Ces modifications sont indexées dans la note de révision.

Enfin, il est effectivement possible d’insérer un bouton sans JavaScript mais il sera impossible de le contrôler sans JavaScript ce qui le rend applicable au critère 7.1. Ce point est explicité par le glossaire : http://www.references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#le-nom-le-rle-la-valeur-le-paramtrage-et-les-changements-dtats

Nous ne voyons pas de raison de modifier cette position.
