### ISSUE TITLE
attribut longdesc

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#31]
Bonjour,
A priori, l'attribut longdesc est obsolète en HTML5. Ne vaudrait-il pas mieux retirer du référentiel les tests le concernant ?
Par exemple : 
Test 1.6.1 : Chaque image porteuse d'information (balise img) qui nécessite une description détaillée, vérifie-t-elle une de ces conditions ?
-  Il existe un attribut longdesc qui donne l'adresse (url) d'une page contenant la description détaillée

**Comment by OlivierNourry** [comment]
Bonjour Giuseppe,

Longdesc est toujours conforme dans la spec HTML5 **du W3C**:
https://www.w3.org/TR/html-longdesc/
En revanche il est possible qu'elle soit mise à la trappe par la spec du
WHAT WG, Hixie ayant toujours été hostile à cet attribut.
Quoiqu'il en soit, du point de vue RGAA c'est la spec W3C qui fera
référence.




[image: --]
Olivier Nourry
[image: http://]about.me/oliviernourry
<http://about.me/oliviernourry>

**Comment by GiuseppeROSA** [comment]
Merci Olivier, 

longdesc estsignalé en erreur sur le validateur :
https://html5.validator.nu/
mais il passe sur le validateur : https://validator.w3.org/

Toutefois, je ne vois plus sa description dans
https://www.w3.org/TR/html5/ 
ni dans les attributs cités directement dans
https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element
ni ceux cités en tant que global attributes sur
https://www.w3.org/TR/html5/dom.html#global-attributes

C'est pourquoi il me semblait qu'il n'était plus autorisé pour HTML5
par le W3C.

Mais effectivement le lien que tu fournis semble indiquer que son usage
est encore possible. La documentation du W3C  ne semble pas très
cohérente.

Encore merci



Cordialement,

  
    
      
      
    
    
      DGFiP
      Giuseppe ROSA
      Inspecteur
Analyste
Atelier SODA - bureau SI-1A
      Site SODA : http://si1a.intranet.dgfip/soda
      
      tel : 01.573.36.997
      pièce :
2388
   
      
    
  



  
    
      
      
        Adoptez
l'éco-attitude. 
      N'imprimez ce mail
que si c'est vraiment nécessaire
      
    
  




-------- Message original --------
Sujet : Re: [rgaa_referentiel] attribut longdesc (#31)
De : Olivier Nourry <notifications@github.com>
Pour : DISIC/rgaa_referentiel
<rgaa_referentiel@noreply.github.com>
Copie à : GiuseppeROSA <giuseppe.rosa@dgfip.finances.gouv.fr>
Date : 10/03/2016 11:17
Bonjour Giuseppe,
  
Longdesc est toujours conforme dans la spec HTML5 **du W3C**:
https://www.w3.org/TR/html-longdesc/
En revanche il est possible qu'elle soit mise à la trappe par la spec du
WHAT WG, Hixie ayant toujours été hostile à cet attribut.
Quoiqu'il en soit, du point de vue RGAA c'est la spec W3C qui fera
référence.
  
  
  
  
[image: --]
Olivier Nourry
[image: http://]about.me/oliviernourry
<http://about.me/oliviernourry>
  
  
Le 9 mars 2016 à 13:23, GiuseppeROSA <notifications@github.com> a
écrit :
  
> Bonjour,
> A priori, l'attribut longdesc est obsolète en HTML5. Ne
vaudrait-il pas
> mieux retirer du référentiel les tests le concernant ?
> Par exemple :
> Test 1.6.1 : Chaque image porteuse d'information (balise img) qui
> nécessite une description détaillée, vérifie-t-elle une de ces
conditions ?
>
> - Il existe un attribut longdesc qui donne l'adresse (url) d'une
page
> contenant la description détaillée
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DISIC/rgaa_referentiel/issues/31>.
>
  —
Reply to this email directly or view
it on GitHub.
