### ISSUE TITLE
note technique critère 9.1

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#32]
au regarde de l'exemple 2 présent sur la technique H42 il serait utile de préciser si le RGAA accepte (comme le fait WCAG) ou pas l'utilisation de h1 n'étant pas en 1er dans l'ordre du code source

https://www.w3.org/TR/WCAG-TECHS/H42.html

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Aucun test de RGAA n’oblige à commencer une hiérarchie de titre par le niveau 1, la seule obligation est que la page doit posséder un titre de niveau 1 au moins.

Le test 9.1.1 : <i>Dans chaque page Web, y a-t-il un titre de niveau 1 (balise `h1` ou balise possédant un rôle ARIA `heading` associé à une propriété `aria-level="1"`) ?</i>

Néanmoins la définition de glossaire a été corrigée pour éviter toute mauvaise interprétation.
