### ISSUE TITLE
img, canvas, svg, object type image dans <button> et <a>

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#33]
Bonjour,

Sauf erreur de ma part le document d'accompagnement ne précise pas un changement important par rapport au RGAA 2.2 à savoir que les cas des liens images et des liens vectoriels est désormais traité dans la thématique Liens au lieu de la thématique Images.

Par ailleurs ces cas ne sont pas clairement exclu au travers des tests de la thématiques images et multimédia du RGAA 3.0. La définition de images porteuses d'informations, média temporel et média non temporel devrait indiquer que si ces éléments sont dans un lien les tests correspondants deviennent non applicables au profit des tests de la thématiques Liens

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

L’entrée de glossaire « Image porteuse d’information » a été modifiée en conséquence. Ces modifications sont indexées dans la note de révision.
