### ISSUE TITLE
Guide d'accompagnement : "4.2.6.1 Dérogations prévues par WCAG 2.0"

### ISSUE THREAD

**Issue by PhilippeVay** [DISIC/rgaa_referentiel#33]
Bonjour,

la section [4.2.6.1 Dérogations prévues par WCAG 2.0 du Guide d'accompagnement](http://references.modernisation.gouv.fr/guide-daccompagnement-0#title-426-liste-des-drogations-admises-et-principe-de-la-compensation) a 2 soucis lorsqu'on l'affiche : 

1. Il n'y a pas de `4.2.6.1.1` alors qu'il y a des `4.2.6.1.2` et `4.2.6.1.3` ([répertoire du dépôt](https://github.com/DISIC/rgaa_referentiel/tree/master/Guide%20d'accompagnement/4.%20Partie%202%20:%20Guide%20d'application%20du%20RGAA/4.2%20Modalit%C3%A9s%20d%E2%80%99application%20du%20RGAA/4.2.6%20Liste%20des%20d%C3%A9rogations%20admises%20et%20principe%20de%20la%20compensation/4.2.6.1%20D%C3%A9rogations%20pr%C3%A9vues%20par%20WCAG%202.0))
2. Dans la section 4.2.6.1.2 actuelle, les 2 titres de niveau 1 sont affichés tels quels après un titre de niveau 6. Ce ne devraient pas être des titres je suppose ? (non pas des h7... :) ) ([répertoire du dépôt](https://github.com/PhilippeVay/rgaa_referentiel/tree/master/Guide%20d'accompagnement/4.%20Partie%202%20:%20Guide%20d'application%20du%20RGAA/4.2%20Modalit%C3%A9s%20d%E2%80%99application%20du%20RGAA/4.2.6%20Liste%20des%20d%C3%A9rogations%20admises%20et%20principe%20de%20la%20compensation/4.2.6.1%20D%C3%A9rogations%20pr%C3%A9vues%20par%20WCAG%202.0/4.2.6.1.2%20Contenus%20fournis%20par%20un%20tiers))

**Comment by philippeBron** [comment]
Bonjour et merci pour votre vigilance.
La correction a été effectuée sur le dépôt github et sera propagée sur le site lors de la prochaine mise à jour.
