### ISSUE TITLE
définition lien image

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#34]
la définition du rgaa 2016 ne prend pas en compte l'utilisation d'aria (aria-label, aria-labelledby à minima) comme source pouvant permettre de  restituer l'intitulé/alternative d'un lien image

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

L’intitulé d’un lien image peut être soit son intitulé seul, donc le contenu de l’attribut `alt’, soit une information de contexte.

Comme le précise la définition de glossaire (http://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#contexte-du-lien), les propriétés `aria-label` et `aria-labelledby` peuvent être utilisées sur tout type de lien.

Nous ne voyons pas de raisons de modifier cette position.
