### ISSUE TITLE
tests 1.3.2, 1.4.3

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#36]
les tests vérifient toujours "Chaque zone (balise area) ..." alors qu'ils devrait vérifier les zones non cliquables car sinon doublon avec 6.1.2

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Le glossaire précise : https://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#zone-dune-image-ractive

« Zone (d’une image réactive) : Zone cliquable ou zone non cliquable d’une image réactive côté client ou zone cliquable d’une image réactive côté serveur. »

Les test 1.3.2 et 1.4.3 concernent donc les deux types de zone.

La référence au critère 6.1 fait référence à la version 2015 de RGAA qui avait déjà traité cette issue. 

Nous ne voyons aucune raison de modifier le RGAA sur ce point.
