### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#4]
A priori, il ne fonctionne pas (Ne trouve même pas RGAA).

**Comment by Etat-Plateforme** [comment]
Bonjour Guiseppe,

Peux-tu préciser le problème ?
Si tu fais référence au moteur de recherche présent sur le site, il fonctionne pour moi. La recherche sur RGAA retourne des résultats que la recherche soit effectuée sur l'ensemble du site ou juste sur le RGAA.

Philippe

**Comment by GiuseppeROSA** [comment]
Bonjour Philippe,

Aujourd'hui cà marche pour moi également. Désolé, c'était peut-être un problème réseau.

Giuseppe

**Comment by Etat-Plateforme** [comment]
Pas de soucis je clôture l'issue.

Philippe
