### ISSUE TITLE
Test 1.8.2

### ISSUE THREAD

**Issue by fhalna** [DISIC/rgaa_referentiel#40]
Dans [la note de révision](https://references.modernisation.gouv.fr/rgaa-accessibilite/changelog.html), 
il est indiqué que le test 1.8.3 devenait le 1.8.2 cependant, dans le nouveau référentiel le test 1.8.2 est différent de l'ancien test 1.8.3.

1.8.2 RGAA 3 2016
Pour chaque bouton "image texte" (balise input avec l’attribut type="image") porteur d’information, en l’absence d’un mécanisme de remplacement, doit si possible être remplacé par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?

1.8.3 RGAA 3
Pour chaque balise form, chacun de ses boutons "image texte" (balise input avec l'attribut type="image") porteuse d'information, en l'absence d'un mécanisme de remplacement, doit si possible être remplacé par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Effectivement on constate une différence entre la note de version et le référentiel. C’est bien la version du test dans le référentiel qui est correcte.
