### ISSUE TITLE
critère 3.3

### ISSUE THREAD

**Issue by fhalna** [DISIC/rgaa_referentiel#43]
l'ensemble des tests du critère 3.3 comporte la possibilité d'utiliser un mécanisme afficher les éléments avec un contraste suffisant. Hors il n'existe aucune mention dans le référentiel sur le fait que l'élément de contrôle du mécanisme réponde au exigence de contraste.

les techniques relatives aux critères font références à la techniques G174 hors celle-ci précise bien dans son intitulé que l'élément de contrôle pour activer ce mécanisme doit avec un contrat suffisant :
"G174: Providing a control with a sufficient contrast ratio that allows users to switch to a presentation that uses sufficient contrast"

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Les tests 3.3.5 et 3.4.5 et la définition de glossaire « Chaque mécanisme qui permet d’afficher le texte avec un rapport de contraste conforme » ont été créés. Ces modifications sont indexées dans la note de révision.
