### ISSUE TITLE
Quelle différence avec votre autre dépôt rgaa_referentiel ?

### ISSUE THREAD

**Issue by PhilippeVay** [DISIC/rgaa_referentiel#47]
Bonjour,

il existe un autre dépôt nommé [rgaa_referentiel](https://github.com/DISIC/rgaa_referentiel).

Je suppose que ce dernier est remplacé par ce dépôt-ci. Dans ce cas, s'il est prévu que cet autre dépôt ne soit plus mis à jour, serait-il s'il vous plaît possible de le préciser dans le [README](https://github.com/DISIC/rgaa_referentiel/blob/master/README.md) de cet autre dépôt ? Cela éviterait à un visiteur de passage (ou aux 35 personnes ayant mis en favori  l'autre dépôt _vs_ 5 pour celui-ci) d'être induit en erreur.

Si ce dépôt ne remplace pas l'autre, je veux bien connaître la différence.

**Comment by dzc34** [comment]
oui le dépôt   https://github.com/DISIC/rgaa_referentiel
est bien le RGAA 3.0 (2015) en FR
donc remplacé par ce dépôt.

**Comment by goetsu** [comment]
ça ne le remplace pas exactement, ce sont deux versions différentes du référentiel il a des projets existant voir encore en dev qui peuvent très bien encore être basés sur l'autre version

**Comment by Etat-Plateforme** [comment]
Bonjour,

Merci pour votre remarque.

Les corrections suivantes ont été apportées aux dépôts des différentes version du Référentiel Général d'Accessibilité pour les Administrations : 
- le dépôt actuel a été renommé rgaa_referentiel pour conserver l'historique des issues et des modifications. Il regroupe désormais les différentes versions du RGAA (RGAA 3.0, RGAA 3 2016 et RGAA 3 2017).
- l'ancien dépôt rgaa_referentiel a été renommé rgaa et pointe vers le dépôt actuel dans son README.
- pour ne pas avoir de lien mort, un nouveau dépôt rgaa_referentiel_3-2016 a été créé et le README redirige vers le dépôt actuel.

Il n'y aura donc plus qu'un dépôt de référence pour le référentiel : https://github.com/DISIC/rgaa_referentiel/

**Comment by dzc34** [comment]
> l’ancien dépôt rgaa_referentiel a été renommé rgaa et pointe vers le dépôt actuel dans son README.

![selection_084](https://user-images.githubusercontent.com/6709977/28853760-16c78752-7733-11e7-9662-e73140eeac0a.png)
pour le dépôt  **rgaa** (version 2015), un descriptif plus explicite éviterait toute confusion (« Ancien dépôt du RGAA 3 2015 » ou « Ancien dépôt du RGAA 3.0 »).

**Comment by Etat-Plateforme** [comment]
Effectivement ! Merci pour cette remarque, c'est modifié.
