### ISSUE TITLE
Critère 6.2.1

### ISSUE THREAD

**Issue by AnneCav** [DISIC/rgaa_referentiel#48]
Un lien devrait pouvoir comporter un titre et un intitulé identiques sans que cela soit considéré non-pertinent dans le cas particulier suivant (l'intitulé est masqué au profit d'une icône au lieu de texte affiché directement) : 

```
<a class="nav-main-item nav-main-home" href="https://mon_site/professionnels/" title="Accueil Professionnels">
   <span class="icon icon-home" aria-hidden="true"></span>
   <span class="blank">Accueil Professionnels</span>
</a>
```

(La class "blank" passe le texte en font-family AdobeBlank.)

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Le glossaire a été complété.

> Note 1 : Par exception, un titre de lien identique à l’intitulé est accepté dans les seuls cas d’un lien image (lien ne contenant que des images), une icône par exemple, ou d’un lien dont le seul contenu visible est une image (lien composite dont le texte est visuellement caché).

Ces modifications sont indexées dans la note de révision.
