### ISSUE TITLE
Respect du RGAA

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#5]
A priori différents éléments ne respectent pas le RGAA (par exemple les tableaux de la base de référence). Par conséquent, le risque de perte de crédibilité est forte.

**Comment by mickaelgirault** [comment]
Bonjour Giuseppe,

A l'époque nous avons débuté le projet avec le framework Bootstrap (qui ne respecte pas le RGAA), car le coût d'un développement accessible était trop important.

**Comment by GiuseppeROSA** [comment]
Bonjour Mickael,

C'est exactement le même argument qu'invoque les projets, alors que le
coût est bien moindre pour un site statique que pour une application
Web. C'est par conséquent un très mauvais message donné aux projets et
un très mauvais exemple puisque étant un site de l'état il aurait du
être accessible (AA RGAA et WCAG) et ce depuis mai 2011.

Par conséquent je ne vois absolument comment "vendre" l'accessibilité
puisque même ceux qui font les référentiels "avouent" qu'ils ne peuvent
pas le respecter !

Devant un tel constat, il aurait fallu laisse à minima le site
précédent qui était accessible. Par ailleurs, des personnes en
situation d'handicap sont eux-mêmes auditeurs accessibilité (EAE
diplôme accessiweb) et Braillenet souhaitait fusionner les deux
référentiels. Je ne sais pas ce qui sera dit lors du séminaire de 25
Juin mais je crois que cela va faire du grabuge.


Cordialement,

  
    
      
      
    
    
      DGFiP
      Giuseppe ROSA
      Inspecteur
Analyste
Atelier SODA - bureau SI-1A
      Site SODA : http://si1a.intranet.dgfip/soda
      
      tel : 01.573.36.997
      pièce :
2388
   
      
    
  



  
    
      
      
        Adoptez
l'éco-attitude. 
      N'imprimez ce mail
que si c'est vraiment nécessaire
      
    
  




-------- Message original --------
Sujet : Re: [rgaa_referentiel] Respect du RGAA (#5)
De : Mickael Girault <notifications@github.com>
Pour : DISIC/rgaa_referentiel
<rgaa_referentiel@noreply.github.com>
Copie à : GiuseppeROSA <giuseppe.rosa@dgfip.finances.gouv.fr>
Date : 18/06/2015 17:33

  Bonjour Giuseppe,
  A l'époque nous avons débuté le projet avec le framework Bootstrap
(qui ne respecte pas le RGAA), car le coût d'un développement
accessible était trop important. 
  —
Reply to this email directly or view
it on GitHub.

**Comment by xam1311** [comment]
Bonjour,
Vous savez que les informations personnelles sont accessibles ?
Que dire du Fail, un site état qui doit être accessible et qui n'a pas été fait sciemment.
Cordialement,

**Comment by OlivierNourry** [comment]
Bonjour Giuseppe,
La réponse faite à ton premier commentaire n'est en aucun cas une réponse émise par la DISIC ou l'un de ses partenaires. D'ailleurs il s'agit visiblement d'une erreur puisque l'auteur (que nous ne connaissons pas) a retiré son message entre temps.
Précisons que la nouvelle version du site du RGAA 3 est générée en HTML à partir de sources en markdown, via un module Drupal. Il y a donc eu visiblement un loupé dans la génération du code HTML, dont nous nous excusons. Ceci sera rectifié dès que possible.
En aucun cas nous n'aurions invoqué un argument de ce genre pour justifier une anomalie d'accessibilité... Et à titre personnel, je partage pleinement ton avis sur la question.
J'espère avoir répondu à tes attentes.

**Comment by GiuseppeROSA** [comment]
Merci pour ces précisions. Je ne comprenais effectivement pas la
position précédente. 

Les hasards (ou non) du calendrier fait que cette refonte du site a
lieu une semaine avant le séminaire AccessiWeb, d'autant plus que le
président également de Braillenet indique sur le site du même nom que
"Désormais, l'activité de BrailleNet concernant l'accessibilité du Web,
en formation
et en labellisation,
se réfèrera au RGAA 3.0." et qu'il l'annoncera probablement au cours de
cette réunion de l'ensemble des Experts Accessibilité en Evaluation.

Mais connaissant et reconnaissant en Olivier un grand acteur de
l'accessibilité du Web, je suis persuadé que tout rentrera très bientôt
dans l'ordre. Et désolé si j'ai semblé m'emporter.


Cordialement,

  
    
      
      
    
    
      DGFiP
      Giuseppe ROSA
      Inspecteur
Analyste
Atelier SODA - bureau SI-1A
      Site SODA : http://si1a.intranet.dgfip/soda
      
      tel : 01.573.36.997
      pièce :
2388
   
      
    
  



  
    
      
      
        Adoptez
l'éco-attitude. 
      N'imprimez ce mail
que si c'est vraiment nécessaire
      
    
  




-------- Message original --------
Sujet : Re: [rgaa_referentiel] Respect du RGAA (#5)
De : Olivier Nourry <notifications@github.com>
Pour : DISIC/rgaa_referentiel
<rgaa_referentiel@noreply.github.com>
Copie à : GiuseppeROSA <giuseppe.rosa@dgfip.finances.gouv.fr>
Date : 19/06/2015 12:25

  Bonjour Giuseppe,
La réponse faite à ton premier commentaire n'est en aucun cas une
réponse émise par la DISIC ou l'un de ses partenaires. D'ailleurs il
s'agit visiblement d'une erreur puisque l'auteur (que nous ne
connaissons pas) a retiré son message entre temps.
Précisons que la nouvelle version du site du RGAA 3 est générée en HTML
à partir de sources en markdown, via un module Drupal. Il y a donc eu
visiblement un loupé dans la génération du code HTML, dont nous nous
excusons. Ceci sera rectifié dès que possible.
En aucun cas nous n'aurions invoqué un argument de ce genre pour
justifier une anomalie d'accessibilité... Et à titre personnel, je
partage pleinement ton avis sur la question.
J'espère avoir répondu à tes attentes.
  —
Reply to this email directly or view
it on GitHub.

**Comment by OlivierNourry** [comment]
Merci pour les compliments :) [sourire].
Le calendrier est tellement joueur qu'en fait, auront lieu le même jour 2 événements totalement différents, et pourtant indirectement liés: d'une part la présentation officielle du RGAA3 (en présence de représentants des associations notamment), et d'autre part, le 21ème Séminaire AccessiWeb... Où Dominique Burger devrait effectivement donner des informations sur l'avenir d'AccessiWeb en tant que référentiel, compte tenu désormais du RGAA3.
Pour le site du RGAA: comme tout nouveau site il y a des imperfections que l'on découvre aufur et à mesure. Merci en tous les cas de toutes tes remontées, elles nous sont très utiles.

**Comment by GiuseppeROSA** [comment]
Si je peux apporter ma pierre à l'édifice, c'est avec plaisir. Si tu as des éléments (actualités...) concernants la présentation officielle, je serais preneur. J'essaie de communiquer dès que je peux sur le sujet en espérant que cela finisse par faire son chemin dans les mentalités.

**Comment by jpv66** [comment]
Bonjour Giuseppe,
Les non conformités actuellement non-traitées (dont celle sur les tableaux) sont référencées dans la déclaration de conformité : 
http://references.modernisation.gouv.fr/declaration-de-conformite-rgaa-30
Elles devraient être traitées rapidement j'imagine.

**Comment by GiuseppeROSA** [comment]
Bonjour Jean-Pierre,

Effectivement, dans la déclaration il est indiqué "les tableaux dans le document d'accompagnement au RGAA et le référentiel technique n'ont pas de titre (en cours de résolution) ;" Par contre il n'est rien n'indiqué concernant les tableaux dans la page référentiel, et notamment que les cellules de contenu ne soient pas reliées aux cellules d'en-têtes (<table><thead><tr><th>Technologie d'assistance</th>
<th>Version TA</th>
<th>Navigateur</th>
</tr></thead><tbody><tr><td>NVDA</td>
<td>Dernière version</td>
<td>Firefox</td>
</tr><tr><td>JAWS</td>
<td>Version précédente</td>
<td>Firefox ou Internet Explorer 9+</td>
</tr><tr><td>Voice Over</td>
<td>Dernière Version</td>
<td>Safari</td>
</tr></tbody></table>)
