### ISSUE TITLE
Critère 3.3 et 3.4 : Hors cas particuliers

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#6]
Le lien "hors cas particuliers" a pour référence #critres-33--34 alors que l'ancre correspondante est #critres-33-34

**Comment by Etat-Plateforme** [comment]
Nous avons pris en note des problèmes d'ancres existant sur le sit et le RGAA en particulier. Nous travaillons à la résolution de ces points dans une prochaine version.
