### ISSUE TITLE
tests 1.3.1, 1.3.2, 1.3.3, 1.4.1, 1.4.2, 1.4.3

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#7]
il a été introduit dans ces tests les conditions suivantes : 
- S’il est présent, le contenu de la propriété aria-label est identique au contenu de l’attribut alt ;
- S’il est présent, le contenu du passage de texte lié via la propriété aria-labelledby est identique au contenu de l’attribut alt.

Le contenu de ces deux attributs prenant le dessus sur le contenu de l'attribut alt si ils sont présent il n'y aucune raison de demander à ce qu'ils soient identiques à l'attribut alt.
Exemple une image porteuse d'info avec un alt="toto" et un aria-labelledby ou un aria-label donnant une alternative pertinente est parfaitement conforme wcag
Si j'en crois la note de révision cela pourrait venir de la raison suivante: 
"Dans le cas de l’utilisation d’un aria-label, l’alternative ne sera pas disponible dans le cas de la désactivation des images. Il est donc nécessaire, la présence de l’attribut alt étant obligatoire, que l’ensemble de ces valeurs est identique"

Néanmoins : 
- cela n'est nullement demandé par wcag
- la restitution de l'attribut alt image désactivé n'est pas standardisé de faite certains navigateur ne le font pas
- cette condition ne saurait s'appliquer à aria-labelledby lorsque cela référence un texte visible

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Pour implémenter une alternative d’image, l’utilisation de `aria-label` et `aria-labelledby` n’est pas autorisée par le RGAA en raison d’un manque de support dans les technologies d’assistance. Il faut donc gérer le cas où ces techniques génériques proposées par WCAG sont utilisées en plus de la technique requise par RGAA par l’intermédiaire de l’utilisation de l’attribut `alt`.

Dans le cas de l’utilisation de `aria-label`, la désactivation des images par le navigateur ou un plugin est susceptible d’afficher uniquement le contenu de l’attribut `alt`. S’il existe une différence entre le contenu de l’attribut `alt` et le contenu de la propriété `aria-label`, l’alternative proposée est susceptible d’être insuffisante.
Par exemple : le contenu de l’attribut `alt` est vide ou contient une valeur non pertinente comme un nom de fichier.

Dans le cas de l’utilisation de `aria-labelledby`, le problème est identique lors d’une désactivation des images. Si le contenu de l’attribut `alt` est renseigné, mais qu’il contient une alternative non pertinente, l’information proposée à l’utilisateur peut poser un problème.

Le fait de réclamer que les valeurs soient identiques permet d’assurer que la même information est transmise quand les images sont désactivées.

Il est normal que WCAG ne demande pas spécifiquement une adaptation de cette nature, puisqu’il propose des techniques de labellisation par l’intermédiaire de propriétés aria qui sont basées sur le calcul de nom accessible.

Dans ce contexte, effectivement, les valeurs implémentées ou liées par les propriétés `aria-label` et `aria-labelledy` écrasent la valeur de l’attribut `alt`, rendant cette exigence inutile.

Néanmoins, cela ne donnera aucune solution directe dans le cas de la désactivation des images.

Lorsque ces deux propriétés pourront être utilisées sur des images, la solution pourrait passer par un nouveau test qui vérifiera que, lorsqu’elles sont employées, le contenu de l’attribut `alt` est vide.

Nous ne voyons pas de raison de modifier le test actuellement implémenté dans RGAA.
