### ISSUE TITLE
Test 13.1.1

### ISSUE THREAD

**Issue by GiuseppeROSA** [DISIC/rgaa_referentiel#7]
Le test 13.1.1 fait mention des procédé de rafraîchissement ou de redirection mais les conditions à respecter ne mentionnent que le rafraîchissement.

Ce test concerne-t-il effectivement la redirection ou au contraire uniquement le rafraîchissement ?

**Comment by OlivierNourry** [comment]
Bonjour Giuseppe,
Il s'agit effectivement d'une erreur de rédaction. Le test 13.1.1 ne devrait concerner que le rafraîchissement; les redirections sont traitées via les tests 13.1.2, 13.1.3, et 13.1.4.
Ces corrections seront intégrées lors de la prochaine mise à jour.

Merci pour ta vigilance!

**Comment by GiuseppeROSA** [comment]
You're welcome !

**Comment by goetsu** [comment]
il pourrait être bien de mettre un label ou une milestone sur les tickets de manière à pouvoir faire le tri entre les tickets fermé car déjà traité, à traité, rejeté, etc

**Comment by Etat-Plateforme** [comment]
Excellente proposition, je regarde comment mettre la mettre en oeuvre.
