### ISSUE TITLE
problème sur les ancres

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#8]
Il y a beaucoup de liens vers les définitions de glossaire / notes techniques / cas particuliers qui ne fonctionnent pas. Il serait utile de refaire une passe dessus pour corriger cela

**Comment by OlivierNourry** [comment]
Bonjour,
Ce problème a été identifié. Il sera traité et corrigé dans la prochaine mise à jour.

Merci pour ta vigilance!

**Comment by Tobino** [comment]
:+1: 
Bonjour,
Même remarque, il y a parfois un double tiret qui traîne dans l'ancre. Il est nécessaire de les supprimer.

exemple:
`#alternative--script` devrait être ` #alternative-script`

**Comment by Etat-Plateforme** [comment]
Nous avons pris en note des problèmes d'ancres existant sur le sit et le RGAA en particulier. Nous travaillons à la résolution de ces points dans une prochaine version.

**Comment by goetsu** [comment]
@Etat-Plateforme est ce que vous avez également corrigé l'absence des liens vers les définitions dans les intitulés de critères ?

**Comment by Etat-Plateforme** [comment]
C'est en cours.
