### ISSUE TITLE
cas particulier caractère obligatoire formulaire mono champ

### ISSUE THREAD

**Issue by goetsu** [DISIC/rgaa_referentiel#9]
Bonjour,

je m'interroge sur l'intérêt de signaler le caractère obligatoire d'un champ lorsqu'il n'y a qu'un seul champ de saisie comme par exemple pour un formulaire d'inscription à une newsletter qui demande juste une adresse email. Il faudrait peut être un cas particulier pour ce type de cas.

**Comment by OlivierNourry** [comment]
Bonjour Aurélien,
Formellement il n'y a aucun critère exigeant que les champs obligatoires soient signalés. Le fait de ne pas signaler un champ obligatoire pose un problème d'utilisabilité du formulaire qui concerne tous les utilisateurs, pas uniquement ceux qui sont en situation de handicap. C'est donc hors périmètre du RGAA.

En revanche, si un champ obligatoire est signalé, il doit l'être de manière accessible, ce que vérifient les tests 11.10.1, 11.10.2,11.10.3.
Si un champ obligatoire requiert un type ou un format spécifique de données, ce type ou ce format doivent être indiqués de manière accessible à l'utilisateur, ce que traitent les tests 11.10.7, 11.10.8, 11.10.9.
Si l'erreur de saisie donne lieu à un message à l'utilisateur, cela doit être fait de manière accessible, ce que traitent les tests 11.10.4, 11.10.5, 11.10.6. Tu noteras que l'émission d'un message en cas d'erreur de saisie n'est pas rendue obligatoire par le RGAA, puisque cela concerne tous les utilisateurs, sans distinction.

J'espère avoir clarifié la question.

**Comment by goetsu** [comment]
au regard des wcag c'est très discutable de ne pas rendre obligatoire l'information sur le caractère obligatoire et les formats avant la saisie notamment avec : http://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html
« Clearly identifying required fields prevents a keyboard only user from submitting an incomplete form and having to navigate the redisplayed form to find the uncompleted field and provide the missing information. »
et dans http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G184 "Required fields are marked with an asterisk (*) and must be filled in to complete the form."

Par ailleurs dans la méthodologie http://disic.github.io/rgaa_methodologie/#formulaire sur les tests 11.10.1, .2 .3, .7, .8, .9 il n'est d'ailleurs nullement mentionné que cela doit se faire après validation

**Comment by goetsu** [comment]
De plus j'ajouterai également que c'était bien un obligatoire d'avoir l'information au préalable en RGAA 2.0 cf http://www.rgaa.net/Presence-d-information-prealable.html

Mais cela dit tout ça ne répond pas à ma question de départ sur le cas particulier du formulaire mono champ ;)

**Comment by access42** [comment]
Bonjour,

Merci beaucoup pour votre retour.

La réponse d'@OlivierNourry nous semble la plus satisfaisante, nous pouvons néanmoins préciser qu'il existe de multiples situations dans lesquelles l'obligation d'indiquer les champs obligatoires serait inutile ou redondante.

Dans le cas du formulaire contenant un champ unique, il faudrait ajouter le cas d'un formulaire de login, la saisie d'un bloc d'adresse, certains types de QCM, certains types de formulaire de confirmation, etc.

La liste des cas particuliers serait alors très longue et susceptible d'être allongée au fur et à mesure des retours ce qui rendrait l'obligation d'indiquer le caractère obligatoire des champs d'un fomulaire indécidable de fait.

Cette problématique de l'indication systématique des champs obligatoires est un problème d'utilisabilité ce qui la situe hors-champ du RGAA.

Nous ne voyons pas de raison de modifier cette position.

Pour ce qui concerne votre retour sur la méthodologie, pourriez-vous la reporter dans le dépot ad'hoc : <a href="https://github.com/DISIC/rgaa_methodologie">DISIC/rgaa_methodologie</a>.

**Comment by goetsu** [comment]
La précision qu'il existe des multiples situations dans lesquelles l'obligation d'indiquer les champs obligatoires serait inutile ou redondante serait effectivement utile.

Par ailleurs, il y a également une mention de la nécessité d'indiquer le caractère obligatoire des champs avant saisie dans http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G131 je m'étonne donc de cette réponse qui me semble allez à l'encontre de l'esprit du SC 3.3.2 

"The intent of this Success Criterion is not to clutter the page with unnecessary information but to provide important cues and instructions that will benefit people with disabilities. Too much information or instruction can be just as much of a hindrance as too little. The goal is to make certain that enough information is provided for the user to accomplish the task without undue confusion or navigation"

L'absence d'information sur la caractère obligatoire des champs avant la validation va bien avoir un impact sur l'accessibilité comme mentionné dans l'exemple déjà mentionné précédemment 

"Clearly identifying required fields prevents a keyboard only user from submitting an incomplete form and having to navigate the redisplayed form to find the uncompleted field and provide the missing information."

**Comment by goetsu** [comment]
et j'oubliais http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/H90 qui est plutôt explicite sur la question

**Comment by Etat-Plateforme** [comment]
@goetsu les réponses de @OlivierNourry et @access42 me semblent répondre à votre question initiale. Nous avons pour ambition de fournir le même niveau d'information à tous. Si le caractère obligatoire n'est pas mentionné est de l'ordre d'un problème général de conception ou d'ergonomie.
Le SC 3.3.2 est de l'ordre de la bonne pratique générale ne s'appliquant pas uniquement qu'au cadre de l'accessibilité. Fournir assez d'information pour permettre aux utilisateurs d'effectuer une tâche est une approche universelle.
Si un champ n'est pas jugé comme devant être marqué comme obligatoire, il ne peut être considéré comme un cas particulier même pour les formulaires mono champ.

**Comment by goetsu** [comment]
Je prend bonne note de votre position, ce qui en amène cependant une nouvelle à savoir quelle est la position concernant les formats de saisie (identique ? différente ?) ?

>  Le SC 3.3.2 est de l'ordre de la bonne pratique générale

Pour la forme une dernière remarque sur cette remarque. Si ce point est dans les WCAG c'est que justement il a bel et bien un impact sur l'accessibilité et non juste un caractère général sinon il n'y serait pas (ce qui d'ailleurs avait fait débat lors de la rédaction des WCAG 2.0). Si tel était le cas c'est l'ensemble de la guidelines 3.3 qui pourrait être considéré comme "bonne pratique" sans rapport avec l'accessibilité et donc permettre par exemple de faire des formulaires sans aucune solution permettant d'associer des étiquettes aux champs sous prétexte que personne n'est discriminé.

Il a globalement été considéré qu'il était généralement plus difficile pour les personnes en situation de handicap de saisir des formulaire et qu'il s'agissait d'un public plus enclin à faire des erreurs de saisie d'où l'existence de la guidelines 3.3.
